// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJMCaeQ2td5wOZ-WsOV6SYCEA1K8bFYuc',
    appId: '1:1075339310730:web:41546aeada61cc912f9f73',
    messagingSenderId: '1075339310730',
    projectId: 'grade-flutter-e6b5f',
    authDomain: 'grade-flutter-e6b5f.firebaseapp.com',
    databaseURL: 'https://grade-flutter-e6b5f-default-rtdb.firebaseio.com',
    storageBucket: 'grade-flutter-e6b5f.appspot.com',
    measurementId: 'G-ZJF1YPRX40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmUTC13WZK6cfLvyqe50iiVQ0f7hC6G-E',
    appId: '1:1075339310730:android:caf75ce9f162c46a2f9f73',
    messagingSenderId: '1075339310730',
    projectId: 'grade-flutter-e6b5f',
    databaseURL: 'https://grade-flutter-e6b5f-default-rtdb.firebaseio.com',
    storageBucket: 'grade-flutter-e6b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83XHkzi1-RjSwuZnn0wIaKzQVFLUPhEs',
    appId: '1:1075339310730:ios:e0f0c9051921f1252f9f73',
    messagingSenderId: '1075339310730',
    projectId: 'grade-flutter-e6b5f',
    databaseURL: 'https://grade-flutter-e6b5f-default-rtdb.firebaseio.com',
    storageBucket: 'grade-flutter-e6b5f.appspot.com',
    iosBundleId: 'com.example.gradeFlutter',
  );
}
